#!/usr/bin/env python3
"""
agent-rules sync harness

Commands:
  sync      Create/fix each target so its agent reads the canonical AGENTS.md
  check     Report whether each target is correctly set up (no changes)
  dry-run   Show what sync would do without touching the filesystem

Target modes (set per target in targets.json; default is "symlink"):
  symlink   The target path is a symlink to the canonical file.
  copy      The target path is a real file generated from the canonical file.
            Use for agents whose instruction loader does not follow symlinks
            (Droid, verified 2026-08-31 on droid CLI 0.208.1).
            Copies go stale when the canonical file changes; re-run sync after
            editing AGENTS.md, and use check to detect staleness.
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

HARNESS_DIR = Path(__file__).resolve().parent
REPO_ROOT = HARNESS_DIR.parent
TARGETS_FILE = HARNESS_DIR / "targets.json"

# First line of every generated copy. Ownership is detected by this prefix, so
# sync can safely overwrite its own stale copies but backs up foreign files.
COPY_MARKER_PREFIX = "<!-- synced by agent-rules harness"


def load_targets():
    with open(TARGETS_FILE) as f:
        data = json.load(f)
    canonical = REPO_ROOT / data["canonical"]
    return canonical, data["targets"]


def expand(p: str) -> Path:
    return Path(os.path.expanduser(p))


def generated_content(canonical: Path) -> str:
    marker = (
        f"{COPY_MARKER_PREFIX} from {canonical} -- do not edit this file; "
        "edit the canonical file and re-run: python3 harness/sync.py sync -->\n\n"
    )
    return marker + canonical.read_text()


def status_for(target: dict, canonical: Path) -> dict:
    link = expand(target["link_path"])
    mode = target.get("mode", "symlink")
    result = {
        "name": target["name"],
        "label": target["label"],
        "link": str(link),
        "canonical": str(canonical),
        "mode": mode,
    }

    if not link.exists() and not link.is_symlink():
        result["status"] = "missing"
        result["detail"] = "does not exist"
        return result

    if mode == "symlink":
        if link.is_symlink():
            dest = link.resolve()
            if dest == canonical.resolve():
                result["status"] = "ok"
                result["detail"] = f"symlink -> {canonical}"
            else:
                result["status"] = "wrong_target"
                result["detail"] = f"symlink -> {dest} (expected {canonical})"
            return result
        result["status"] = "regular_file"
        result["detail"] = "exists as regular file, not a symlink"
        return result

    # mode == "copy"
    if link.is_symlink():
        result["status"] = "is_symlink"
        result["detail"] = "is a symlink, but this agent needs a real file (its loader does not follow symlinks)"
        return result

    content = link.read_text()
    if content == generated_content(canonical):
        result["status"] = "ok"
        result["detail"] = f"copy of {canonical} (current)"
    elif content.startswith(COPY_MARKER_PREFIX):
        result["status"] = "stale"
        result["detail"] = "generated copy is out of date with the canonical file"
    else:
        result["status"] = "foreign_file"
        result["detail"] = "exists as a regular file not generated by this harness"
    return result


ICONS = {
    "ok": "OK",
    "missing": "MISSING",
    "wrong_target": "WRONG",
    "regular_file": "FILE",
    "is_symlink": "LINK",
    "stale": "STALE",
    "foreign_file": "FILE",
}


def print_status(s: dict, prefix: str = ""):
    tag = ICONS.get(s["status"], s["status"].upper())
    print(f"  {prefix}[{tag:>7}]  {s['label']:<20}  {s['link']}")
    if s["status"] != "ok":
        print(f"           {'':20}  {s['detail']}")


def cmd_check(args):
    canonical, targets = load_targets()
    if not canonical.exists():
        print(f"ERROR: canonical file not found: {canonical}")
        sys.exit(1)

    all_ok = True
    print(f"Canonical: {canonical}\n")
    for t in targets:
        s = status_for(t, canonical)
        print_status(s)
        if s["status"] != "ok":
            all_ok = False

    print()
    if all_ok:
        print("All targets are correctly set up.")
        print("Note: this verifies the filesystem only. Run 'python3 harness/verify.py'")
        print("to prove each agent actually loads the rules into a fresh session.")
    else:
        print("Some targets need attention. Run 'sync' to fix.")
        sys.exit(1)


def plan_actions(target: dict, status: dict, canonical: Path):
    """Return the list of (action, detail) steps sync would take for a target."""
    link = expand(target["link_path"])
    mode = status["mode"]
    actions = []

    if status["status"] == "ok":
        return actions

    if not link.parent.exists():
        actions.append(("MKDIR", str(link.parent)))

    if status["status"] in ("regular_file", "foreign_file"):
        backup = link.with_suffix(link.suffix + ".bak")
        actions.append(("BACKUP", f"{link} -> {backup}"))

    if mode == "symlink":
        actions.append(("LINK", f"{link} -> {canonical}"))
    else:
        actions.append(("COPY", f"{canonical} -> {link}"))
    return actions


def cmd_dryrun(args):
    canonical, targets = load_targets()
    if not canonical.exists():
        print(f"ERROR: canonical file not found: {canonical}")
        sys.exit(1)

    print(f"Canonical: {canonical}\n")
    print("Dry run -- no changes will be made:\n")
    changes = 0
    for t in targets:
        s = status_for(t, canonical)
        actions = plan_actions(t, s, canonical)
        if not actions:
            print(f"  [  SKIP]  {t['label']:<20}  already correct")
            continue
        changes += 1
        for action, detail in actions:
            print(f"  [{action:>6}]  {t['label']:<20}  {detail}")

    print()
    if changes == 0:
        print("Nothing to do.")
    else:
        print(f"{changes} target(s) would be changed. Run 'sync' to apply.")


def cmd_sync(args):
    canonical, targets = load_targets()
    if not canonical.exists():
        print(f"ERROR: canonical file not found: {canonical}")
        sys.exit(1)

    print(f"Canonical: {canonical}\n")
    changed = 0
    for t in targets:
        s = status_for(t, canonical)
        link = expand(t["link_path"])

        if s["status"] == "ok":
            print(f"  [  SKIP]  {t['label']:<20}  already correct")
            continue

        for action, detail in plan_actions(t, s, canonical):
            if action == "MKDIR":
                link.parent.mkdir(parents=True, exist_ok=True)
            elif action == "BACKUP":
                backup = link.with_suffix(link.suffix + ".bak")
                shutil.move(str(link), str(backup))
            elif action == "LINK":
                if link.is_symlink():
                    link.unlink()
                link.symlink_to(canonical)
            elif action == "COPY":
                if link.is_symlink():
                    link.unlink()
                link.write_text(generated_content(canonical))
            print(f"  [{action:>6}]  {t['label']:<20}  {detail}")
        changed += 1

    print()
    if changed == 0:
        print("Everything was already in sync.")
    else:
        print(f"Synced {changed} target(s).")


def main():
    parser = argparse.ArgumentParser(
        prog="agent-rules",
        description="Sync a canonical AGENTS.md to all your coding agents.",
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("sync", help="Create or fix all targets (symlinks and copies)")
    sub.add_parser("check", help="Verify all targets are correctly set up")
    sub.add_parser("dry-run", help="Show what sync would do without changes")

    args = parser.parse_args()
    if args.command is None:
        parser.print_help()
        sys.exit(0)

    cmds = {"sync": cmd_sync, "check": cmd_check, "dry-run": cmd_dryrun}
    cmds[args.command](args)


if __name__ == "__main__":
    main()
